// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU-qiEcg3GLz4HtF-L5jHbTz5ztNVM-1U',
    appId: '1:496952247128:web:02867563a7b93df3529b2d',
    messagingSenderId: '496952247128',
    projectId: 'pet-care-5c892',
    authDomain: 'pet-care-5c892.firebaseapp.com',
    storageBucket: 'pet-care-5c892.appspot.com',
    measurementId: 'G-BW7GKBE855',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwqt7qOug78SJ5Ve94cdZh30XoS3pf5t4',
    appId: '1:496952247128:android:9d7a82d8d92b1d7d529b2d',
    messagingSenderId: '496952247128',
    projectId: 'pet-care-5c892',
    storageBucket: 'pet-care-5c892.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3KbBCcDRQoG8Hi9K8JiMlE8D80FPuPbg',
    appId: '1:496952247128:ios:970180ebacaf3cb1529b2d',
    messagingSenderId: '496952247128',
    projectId: 'pet-care-5c892',
    storageBucket: 'pet-care-5c892.appspot.com',
    iosClientId: '496952247128-h8h7177q0h0nfgd9hboqg4eetkg9k7kk.apps.googleusercontent.com',
    iosBundleId: 'com.example.petcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3KbBCcDRQoG8Hi9K8JiMlE8D80FPuPbg',
    appId: '1:496952247128:ios:970180ebacaf3cb1529b2d',
    messagingSenderId: '496952247128',
    projectId: 'pet-care-5c892',
    storageBucket: 'pet-care-5c892.appspot.com',
    iosClientId: '496952247128-h8h7177q0h0nfgd9hboqg4eetkg9k7kk.apps.googleusercontent.com',
    iosBundleId: 'com.example.petcare',
  );
}
